#!/bin/bash
# Helper script to find Railway URLs

echo "🔍 Finding Railway Service URLs"
echo ""
echo "Your Railway Project:"
echo "https://railway.com/project/28c1b5b3-fbcf-44f8-b9f7-17d74ea25df1?environmentId=8f3d4717-e177-4f69-b706-9179bd78dc3b"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Steps to Get URLs:"
echo ""
echo "1. Open the Railway dashboard link above"
echo "2. For EACH service (NBA, SHAP, BetInput):"
echo "   - Click on the service name"
echo "   - Go to 'Settings' → 'Networking'"
echo "   - Copy the 'Public Domain' URL"
echo "   - Or click 'Generate Domain' if none exists"
echo ""
echo "3. Test each URL:"
echo "   curl https://your-url.railway.app/games          # NBA"
echo "   curl https://your-url.railway.app/api/health    # BetInput"
echo "   curl https://your-url.railway.app/api/predictions/live  # SHAP"
echo ""
echo "4. Create .env file with your URLs:"
echo "   VITE_NBA_API_URL=https://your-nba-url.railway.app"
echo "   VITE_SHAP_API_URL=https://your-shap-url.railway.app"
echo "   VITE_BETINPUT_API_URL=https://your-betinput-url.railway.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ All services are running on Railway!"
echo "   - BetInput: ✅ Running"
echo "   - NBA: ✅ Running"
echo "   - SHAP: ✅ Running"
echo ""
echo "Once you have the URLs, update .env and run:"
echo "   npm run dev"
echo ""

